name: 🚀 Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    name: Build and publish Python package to PyPI
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install pip
        run: pip install --upgrade pip

      - name: Install Python packages
        run: pip install --upgrade build twine

      - name: Extract tag name
        id: tag
        run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Build wheels
        run: python -m build

      - name: Check PyPI description
        run: python -m twine check dist/*

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          verbose: true

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true