name: 🚀 Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and publish Python package to PyPI
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install pip
        run: pip install --upgrade pip

      - name: Install Python packages
        run: pip install --upgrade build twine

      - name: Build wheels
        run: python -m build

      - name: Check PyPI description
        run: python -m twine check dist/*

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true

      - name: Publish release notes on GitHub
        run: gh release create ${TAG} -F CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
          TAG: ${{ github.ref_name }}